version: "2"

run:
  timeout: 5m
  issues-exit-code: 1
  tests: true
  modules-download-mode: readonly

linters:
  enable:
    - dupl          # Code duplication detection
    - goconst       # Duplicate string literals
    - gofmt         # Go formatting
    - goimports     # Import management
    - govet         # Go vet analysis
    - errcheck      # Error checking
    - staticcheck   # Static analysis
    - unused        # Unused code detection
    - gosimple      # Simplification suggestions

linters-settings:
  dupl:
    threshold: 100  # Tokens count to trigger issue (adjustable)
  
  goconst:
    min-len: 2      # Minimal length of string constant
    min-occurrences: 2 # Minimum occurrences to trigger issue

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-rules:
    # Exclude some linters from running on tests files
    - path: _test\.go
      linters:
        - dupl     # Allow some duplication in tests
        - goconst  # Allow string constants in tests

output:
  print-issued-lines: true
  print-linter-name: true
  sort-results: true