version: "2"
run:
  timeout: 10m
  go: 1.26.1
  build-tags:
    - goexperiment.arenas
    - goexperiment.goroutineleakprofile
    - goexperiment.jsonv2
    - goexperiment.runtimesecret
    - goexperiment.simd
  modules-download-mode: readonly
  allow-parallel-runners: true
  allow-serial-runners: true
  issues-exit-code: 1
  tests: true
output:
  formats: {}
linters:
  enable:
    - bodyclose
    - contextcheck
    - copyloopvar
    - cyclop
    - dupl
    - durationcheck
    - err113
    - errcheck
    - errchkjson
    - errname
    - errorlint
    - exhaustive
    - exhaustruct
    - forcetypeassert
    - funlen
    - ginkgolinter
    - gochecknoglobals
    - gochecknoinits
    - gochecksumtype
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - gosec
    - gosmopolitan
    - govet
    - ineffassign
    - interfacebloat
    - intrange
    - loggercheck
    - maintidx
    - mirror
    - misspell
    - musttag
    - nakedret
    - nestif
    - nilerr
    - nilnesserr
    - nilnil
    - noctx
    - nolintlint
    - paralleltest
    - perfsprint
    - prealloc
    - predeclared
    - protogetter
    - reassign
    - recvcheck
    - revive
    - rowserrcheck
    - sloglint
    - spancheck
    - sqlclosecheck
    - testifylint
    - thelper
    - unconvert
    - unparam
    - unused
    - usetesting
    - wastedassign
    - wrapcheck
    - zerologlint
formatters:
  enable:
    - gci
    - goimports
    - gofumpt
    - golines
issues: {}
