package api

// Type definitions generated from TypeSpec
// These should be generated by TypeSpec compiler in production

type PublicConfig struct {
	Version      string                     `json:"version"`
	SafeMode     bool                       `json:"safeMode"`
	MaxDiskUsage  int32                      `json:"maxDiskUsage"`
	ProtectedPaths []string                  `json:"protectedPaths"`
	Profiles      map[string]*PublicProfile  `json:"profiles"`
}

type PublicProfile struct {
	Name        string           `json:"name"`
	Description string           `json:"description"`
	Enabled     bool             `json:"enabled"`
	Operations  []PublicOperation `json:"operations"`
}

type PublicOperation struct {
	Name        string           `json:"name"`
	Description string           `json:"description"`
	RiskLevel   PublicRiskLevel  `json:"riskLevel"`
	Enabled     bool             `json:"enabled"`
	Settings    OperationSettings `json:"settings"`
}

type OperationSettings struct {
	DryRun             bool `json:"dryRun"`
	Verbose            bool `json:"verbose"`
	TimeoutSeconds     int32 `json:"timeoutSeconds"`
	ConfirmBeforeDelete bool `json:"confirmBeforeDelete"`
}

type PublicCleanResult struct {
	Success     bool           `json:"success"`
	FreedBytes  uint64         `json:"freedBytes"`
	ItemsRemoved uint32         `json:"itemsRemoved"`
	ItemsFailed uint32         `json:"itemsFailed"`
	CleanTime   string         `json:"cleanTime"` // ISO 8601 duration
	CleanedAt   string         `json:"cleanedAt"` // ISO 8601 timestamp
	Strategy    PublicStrategy `json:"strategy"`
	Errors      []string       `json:"errors,omitempty"`
}

type PublicRiskLevel string

const (
	PublicRiskLow      PublicRiskLevel = "LOW"
	PublicRiskMedium   PublicRiskLevel = "MEDIUM"
	PublicRiskHigh     PublicRiskLevel = "HIGH"
	PublicRiskCritical PublicRiskLevel = "CRITICAL"
)

type PublicStrategy string

const (
	PublicStrategyAggressive   PublicStrategy = "aggressive"
	PublicStrategyConservative PublicStrategy = "conservative"
	PublicStrategyDryRun      PublicStrategy = "dry-run"
)

// OperationType represents types of cleanup operations
type OperationType string

const (
	OperationTypeNixGenerations OperationType = "nix-generations"
	OperationTypeTempFiles      OperationType = "temp-files"
	OperationTypeLogFiles       OperationType = "log-files"
	OperationTypeCacheFiles     OperationType = "cache-files"
)

// CleanRequest represents a cleaning request with type-safe operations
type CleanRequest struct {
	Config     PublicConfig   `json:"config"`
	Strategy   PublicStrategy `json:"strategy"`
	Operations []OperationType `json:"operations"`
	DryRun     *bool          `json:"dryRun,omitempty"`
}