// Code generated by "stringer -type=ChangeOperationType"; DO NOT EDIT.

package shared

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ChangeOperationAddedType-0]
	_ = x[ChangeOperationRemovedType-1]
	_ = x[ChangeOperationModifiedType-2]
}

const _ChangeOperationType_name = "ChangeOperationAddedTypeChangeOperationRemovedTypeChangeOperationModifiedType"

var _ChangeOperationType_index = [...]uint8{0, 24, 50, 77}

func (i ChangeOperationType) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_ChangeOperationType_index)-1 {
		return "ChangeOperationType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ChangeOperationType_name[_ChangeOperationType_index[idx]:_ChangeOperationType_index[idx+1]]
}
