// Code generated by "stringer -type=CleanStrategyType"; DO NOT EDIT.

package shared

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[StrategyAggressiveType-0]
	_ = x[StrategyConservativeType-1]
	_ = x[StrategyDryRunType-2]
}

const _CleanStrategyType_name = "StrategyAggressiveTypeStrategyConservativeTypeStrategyDryRunType"

var _CleanStrategyType_index = [...]uint8{0, 22, 46, 64}

func (i CleanStrategyType) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_CleanStrategyType_index)-1 {
		return "CleanStrategyType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _CleanStrategyType_name[_CleanStrategyType_index[idx]:_CleanStrategyType_index[idx+1]]
}
