// Code generated by "stringer -type=EnforcementLevelType"; DO NOT EDIT.

package shared

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[EnforcementLevelNoneType-0]
	_ = x[EnforcementLevelWarningType-1]
	_ = x[EnforcementLevelStrictType-2]
	_ = x[EnforcementLevelCriticalType-3]
}

const _EnforcementLevelType_name = "EnforcementLevelNoneTypeEnforcementLevelWarningTypeEnforcementLevelStrictTypeEnforcementLevelCriticalType"

var _EnforcementLevelType_index = [...]uint8{0, 24, 51, 77, 105}

func (i EnforcementLevelType) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_EnforcementLevelType_index)-1 {
		return "EnforcementLevelType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _EnforcementLevelType_name[_EnforcementLevelType_index[idx]:_EnforcementLevelType_index[idx+1]]
}
