// Code generated by "stringer -type=ExecutionModeType"; DO NOT EDIT.

package shared

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ExecutionModeSequentialType-0]
	_ = x[ExecutionModeParallelType-1]
	_ = x[ExecutionModeBatchType-2]
	_ = x[ExecutionModeInteractiveType-3]
}

const _ExecutionModeType_name = "ExecutionModeSequentialTypeExecutionModeParallelTypeExecutionModeBatchTypeExecutionModeInteractiveType"

var _ExecutionModeType_index = [...]uint8{0, 27, 52, 74, 102}

func (i ExecutionModeType) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_ExecutionModeType_index)-1 {
		return "ExecutionModeType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ExecutionModeType_name[_ExecutionModeType_index[idx]:_ExecutionModeType_index[idx+1]]
}
