// Code generated by "stringer -type=FileSelectionStrategyType"; DO NOT EDIT.

package shared

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[FileSelectionStrategyAllType-0]
	_ = x[FileSelectionStrategySizeType-1]
	_ = x[FileSelectionStrategyTypeType-2]
	_ = x[FileSelectionStrategyDateType-3]
	_ = x[FileSelectionStrategyPatternType-4]
}

const _FileSelectionStrategyType_name = "FileSelectionStrategyAllTypeFileSelectionStrategySizeTypeFileSelectionStrategyTypeTypeFileSelectionStrategyDateTypeFileSelectionStrategyPatternType"

var _FileSelectionStrategyType_index = [...]uint8{0, 28, 57, 86, 115, 147}

func (i FileSelectionStrategyType) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_FileSelectionStrategyType_index)-1 {
		return "FileSelectionStrategyType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _FileSelectionStrategyType_name[_FileSelectionStrategyType_index[idx]:_FileSelectionStrategyType_index[idx+1]]
}
