// Code generated by "stringer -type=OperationNameType"; DO NOT EDIT.

package shared

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[OperationNameNixGenerations-0]
	_ = x[OperationNameHomebrew-1]
	_ = x[OperationNamePackageCache-2]
	_ = x[OperationNameTempFiles-3]
	_ = x[OperationNameSystemTemp-4]
}

const _OperationNameType_name = "OperationNameNixGenerationsOperationNameHomebrewOperationNamePackageCacheOperationNameTempFilesOperationNameSystemTemp"

var _OperationNameType_index = [...]uint8{0, 27, 48, 73, 95, 118}

func (i OperationNameType) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_OperationNameType_index)-1 {
		return "OperationNameType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _OperationNameType_name[_OperationNameType_index[idx]:_OperationNameType_index[idx+1]]
}
