// Code generated by "stringer -type=OptimizationLevelType"; DO NOT EDIT.

package shared

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[OptimizationLevelNoneType-0]
	_ = x[OptimizationLevelBasicType-1]
	_ = x[OptimizationLevelAggressiveType-2]
	_ = x[OptimizationLevelMaximumType-3]
}

const _OptimizationLevelType_name = "OptimizationLevelNoneTypeOptimizationLevelBasicTypeOptimizationLevelAggressiveTypeOptimizationLevelMaximumType"

var _OptimizationLevelType_index = [...]uint8{0, 25, 51, 82, 110}

func (i OptimizationLevelType) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_OptimizationLevelType_index)-1 {
		return "OptimizationLevelType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _OptimizationLevelType_name[_OptimizationLevelType_index[idx]:_OptimizationLevelType_index[idx+1]]
}
