// Code generated by "stringer -type=RecursionLevelType"; DO NOT EDIT.

package shared

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[RecursionLevelNoneType-0]
	_ = x[RecursionLevelShallowType-1]
	_ = x[RecursionLevelMediumType-2]
	_ = x[RecursionLevelDeepType-3]
	_ = x[RecursionLevelFullType-4]
}

const _RecursionLevelType_name = "RecursionLevelNoneTypeRecursionLevelShallowTypeRecursionLevelMediumTypeRecursionLevelDeepTypeRecursionLevelFullType"

var _RecursionLevelType_index = [...]uint8{0, 22, 47, 71, 93, 115}

func (i RecursionLevelType) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_RecursionLevelType_index)-1 {
		return "RecursionLevelType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _RecursionLevelType_name[_RecursionLevelType_index[idx]:_RecursionLevelType_index[idx+1]]
}
