// Code generated by "stringer -type=RiskLevelType"; DO NOT EDIT.

package shared

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[RiskLevelLowType-0]
	_ = x[RiskLevelMediumType-1]
	_ = x[RiskLevelHighType-2]
	_ = x[RiskLevelCriticalType-3]
}

const _RiskLevelType_name = "RiskLevelLowTypeRiskLevelMediumTypeRiskLevelHighTypeRiskLevelCriticalType"

var _RiskLevelType_index = [...]uint8{0, 16, 35, 52, 73}

func (i RiskLevelType) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_RiskLevelType_index)-1 {
		return "RiskLevelType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _RiskLevelType_name[_RiskLevelType_index[idx]:_RiskLevelType_index[idx+1]]
}
