// Code generated by "stringer -type=SafetyLevelType"; DO NOT EDIT.

package shared

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[SafetyLevelUnsafeType-0]
	_ = x[SafetyLevelSafeType-1]
	_ = x[SafetyLevelStrictType-2]
	_ = x[SafetyLevelParanoidType-3]
}

const _SafetyLevelType_name = "SafetyLevelUnsafeTypeSafetyLevelSafeTypeSafetyLevelStrictTypeSafetyLevelParanoidType"

var _SafetyLevelType_index = [...]uint8{0, 21, 40, 61, 84}

func (i SafetyLevelType) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_SafetyLevelType_index)-1 {
		return "SafetyLevelType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _SafetyLevelType_name[_SafetyLevelType_index[idx]:_SafetyLevelType_index[idx+1]]
}
