// Code generated by "stringer -type=ScanTypeType"; DO NOT EDIT.

package shared

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ScanTypeNixStoreType-0]
	_ = x[ScanTypeHomebrewType-1]
	_ = x[ScanTypePackageCacheType-2]
	_ = x[ScanTypeTempType-3]
	_ = x[ScanTypeSystemType-4]
}

const _ScanTypeType_name = "ScanTypeNixStoreTypeScanTypeHomebrewTypeScanTypePackageCacheTypeScanTypeTempTypeScanTypeSystemType"

var _ScanTypeType_index = [...]uint8{0, 20, 40, 64, 80, 98}

func (i ScanTypeType) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_ScanTypeType_index)-1 {
		return "ScanTypeType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ScanTypeType_name[_ScanTypeType_index[idx]:_ScanTypeType_index[idx+1]]
}
