// Code generated by "stringer -type=SelectedStatusType"; DO NOT EDIT.

package shared

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[SelectedStatusNotSelectedType-0]
	_ = x[SelectedStatusSelectedType-1]
	_ = x[SelectedStatusPartialType-2]
	_ = x[SelectedStatusExcludedType-3]
}

const _SelectedStatusType_name = "SelectedStatusNotSelectedTypeSelectedStatusSelectedTypeSelectedStatusPartialTypeSelectedStatusExcludedType"

var _SelectedStatusType_index = [...]uint8{0, 29, 55, 80, 106}

func (i SelectedStatusType) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_SelectedStatusType_index)-1 {
		return "SelectedStatusType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _SelectedStatusType_name[_SelectedStatusType_index[idx]:_SelectedStatusType_index[idx+1]]
}
