// Code generated by "stringer -type=StatusType"; DO NOT EDIT.

package shared

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[StatusInactiveType-0]
	_ = x[StatusActiveType-1]
	_ = x[StatusCompletedType-2]
	_ = x[StatusFailedType-3]
	_ = x[StatusPendingType-4]
}

const _StatusType_name = "StatusInactiveTypeStatusActiveTypeStatusCompletedTypeStatusFailedTypeStatusPendingType"

var _StatusType_index = [...]uint8{0, 18, 34, 53, 69, 86}

func (i StatusType) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_StatusType_index)-1 {
		return "StatusType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _StatusType_name[_StatusType_index[idx]:_StatusType_index[idx+1]]
}
