// Code generated by "stringer -type=ValidationLevelType"; DO NOT EDIT.

package shared

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ValidationLevelNoneType-0]
	_ = x[ValidationLevelBasicType-1]
	_ = x[ValidationLevelComprehensiveType-2]
	_ = x[ValidationLevelStrictType-3]
}

const _ValidationLevelType_name = "ValidationLevelNoneTypeValidationLevelBasicTypeValidationLevelComprehensiveTypeValidationLevelStrictType"

var _ValidationLevelType_index = [...]uint8{0, 23, 47, 79, 104}

func (i ValidationLevelType) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_ValidationLevelType_index)-1 {
		return "ValidationLevelType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ValidationLevelType_name[_ValidationLevelType_index[idx]:_ValidationLevelType_index[idx+1]]
}
